# Content

In [2]:
import tensorflow as tf
import keras
from keras import layers
import numpy as np

2024-04-19 15:29:27.777638: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-04-19 15:29:33.357260: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [14]:
#set seed
tf.keras.utils.set_random_seed(96)

#set the sequential model with 3 layers
model = keras.Sequential(
    [
        layers.Dense(units=2, activation='relu', name='layer1'),
        layers.Dense(units=3, activation='relu', name='layer2'),
        layers.Dense(units=4, name='layer3'),

    ]
)

#call the sequential model
x = tf.ones((3,3))
y = model(x)
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.69751585, -0.89238983, -0.15444523, -0.1564925 ],
       [-0.69751585, -0.89238983, -0.15444523, -0.1564925 ],
       [-0.69751585, -0.89238983, -0.15444523, -0.1564925 ]],
      dtype=float32)>

In [66]:
#equivalent model to the above

#set seed
tf.keras.utils.set_random_seed(96)

#set the sequential model with 3 layers
layer1 = layers.Dense(units=2, activation='relu', name='layer1')
layer2 = layers.Dense(units=3, activation='relu', name='layer2')
layer3 = layers.Dense(units=4, name='layer3')
#call the sequential model
x = tf.ones((3,3))
y = layer3(layer2(layer1(x)))
y


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.69751585, -0.89238983, -0.15444523, -0.1564925 ],
       [-0.69751585, -0.89238983, -0.15444523, -0.1564925 ],
       [-0.69751585, -0.89238983, -0.15444523, -0.1564925 ]],
      dtype=float32)>

We conclude it is actually the same Sequential model constructions

In [6]:
layer = layers.Dense(units=3)
layer.weights  # Empty

[]

In [5]:
# layer weights after entering the inputs
x = tf.ones((1,4))
y = layer(x)
layer.weights

[<tf.Variable 'dense/kernel:0' shape=(4, 3) dtype=float32, numpy=
 array([[ 0.11403227,  0.37307203, -0.3158257 ],
        [ 0.2862811 , -0.8418399 , -0.49150178],
        [-0.90049213, -0.6906144 ,  0.05955148],
        [-0.16262174,  0.22929382, -0.50861406]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]

In [4]:
model = keras.Sequential(
    [
        layers.Dense(2, activation="relu"),
        layers.Dense(3, activation="relu"),
        layers.Dense(4),
    ]
)

In [6]:
# error type of the model when there is not inputs
model.weights

ValueError: Weights for model 'sequential_1' have not yet been created. Weights are created when the model is first called on inputs or `build()` is called with an `input_shape`.

In [8]:
model.summary()

ValueError: This model has not yet been built. Build the model first by calling `build()` or by calling the model on a batch of data.

In [6]:
#building the model
model = keras.Sequential(
    [
        layers.Dense(2, activation="relu"),
        layers.Dense(3, activation="relu"),
        layers.Dense(4),
    ]
) 

x = tf.ones((2, 4))
y = model(x)
print("Number of weights after calling the model:", len(model.weights))  # 6

Number of weights after calling the model: 6


In [7]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (2, 2)                    10        
                                                                 
 dense_7 (Dense)             (2, 3)                    9         
                                                                 
 dense_8 (Dense)             (2, 4)                    16        
                                                                 
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


In [21]:
#step-by-step model display
model = keras.Sequential(
    [
        keras.Input(shape=(4,)),
        layers.Dense(2, activation="relu"),
        layers.Dense(3),
    ]
) 

In [22]:
model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_15 (Dense)            (None, 2)                 10        
                                                                 
 dense_16 (Dense)            (None, 3)                 9         
                                                                 
Total params: 19
Trainable params: 19
Non-trainable params: 0
_________________________________________________________________


In [23]:
model.weights

[<tf.Variable 'dense_15/kernel:0' shape=(4, 2) dtype=float32, numpy=
 array([[ 0.2468965 , -0.3607421 ],
        [-0.6160872 , -0.09327173],
        [-0.35170126, -0.9121363 ],
        [-0.15791225, -0.61642647]], dtype=float32)>,
 <tf.Variable 'dense_15/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'dense_16/kernel:0' shape=(2, 3) dtype=float32, numpy=
 array([[-0.6551687 , -0.17583728, -0.05381632],
        [ 0.9569249 , -0.41870528, -1.0778964 ]], dtype=float32)>,
 <tf.Variable 'dense_16/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]

In [4]:
model = keras.Sequential()
model.add(keras.Input(shape=(250, 250, 3)))  # 250x250 RGB images
model.add(layers.Conv2D(32, 5, strides=2, activation="relu"))
model.add(layers.Conv2D(32, 3, activation="relu"))
# model.add(layers.MaxPooling2D(3))

# Can you guess what the current output shape is at this point? Probably not.
# Let's just print it:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_2 (Conv2D)           (None, 123, 123, 32)      2432      
                                                                 
 conv2d_3 (Conv2D)           (None, 121, 121, 32)      9248      
                                                                 
Total params: 11,680


Trainable params: 11,680
Non-trainable params: 0
_________________________________________________________________


# Test

In [111]:
import tensorflow as tf
import numpy as np

In [210]:
# seed
np.random.seed(96)

# input tensor and kernel
x = np.random.rand(4,4)
kernel = np.array([[1,-1],[-1,1]])

## TensorFlow


The typical shape of an image tensor in TensorFlow is [batch_size, height, width, channels], where:

- batch_size: number of images in a batch.
- height: height of each image in pixels.
- width: width of each image in pixels.
- channels: number of color channels in each image (e.g., 3 for RGB images).

while the usual kernel shape in TensorFlow [filter_height, filter_width, input_channels, output_channels], where:

- filter_height: The height of the kernel.
- filter_width: The width of the kernel.
- input_channels: The number of input channels the kernel operates on.
- output_channels: The number of output channels produced by the kernel.

In [211]:
# tensor/kernel reshape for grayscale one image

x_tf = tf.constant(x, dtype=tf.float32)
x_tf = tf.reshape(x_tf, [1, x_tf.shape[0],x_tf.shape[1],1])

kernel_tf = tf.constant(kernel, dtype=tf.float32)
kernel_tf = tf.reshape(kernel_tf, [2, 2, 1, 1])


In [254]:
tf.nn.conv2d(x_tf,kernel_tf,strides=(1,1),padding='VALID')


<tf.Tensor: shape=(1, 3, 3, 1), dtype=float32, numpy=
array([[[[-1.2836186 ],
         [ 0.06659165],
         [ 0.38292804]],

        [[ 0.05634803],
         [ 0.3132659 ],
         [-0.5053024 ]],

        [[ 0.32573864],
         [-0.28769332],
         [-0.12484254]]]], dtype=float32)>

## By hand

In [252]:
n = kernel.shape[0]
m = x.shape[0]

storage = []
for i in range(m-n+1):
    for j in range(m-n+1):
        element = np.array([x[i][0+j:n+j],x[i+1][0+j:n+j]])
        sum_element = np.sum(np.multiply(element,kernel))
        storage.append(sum_element)


result = np.reshape(np.array(storage),(3,3))
result

array([[-1.28361855,  0.06659161,  0.38292808],
       [ 0.05634807,  0.31326589, -0.50530246],
       [ 0.32573864, -0.28769333, -0.12484254]])