In [2]:
import tensorflow as tf
import keras
from keras import layers
import numpy as np

2024-03-23 18:19:49.534458: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-23 18:19:54.229556: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [14]:
#set seed
tf.keras.utils.set_random_seed(96)

#set the sequential model with 3 layers
model = keras.Sequential(
    [
        layers.Dense(units=2, activation='relu', name='layer1'),
        layers.Dense(units=3, activation='relu', name='layer2'),
        layers.Dense(units=4, name='layer3'),

    ]
)

#call the sequential model
x = tf.ones((3,3))
y = model(x)
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.69751585, -0.89238983, -0.15444523, -0.1564925 ],
       [-0.69751585, -0.89238983, -0.15444523, -0.1564925 ],
       [-0.69751585, -0.89238983, -0.15444523, -0.1564925 ]],
      dtype=float32)>

In [66]:
#equivalent model to the above

#set seed
tf.keras.utils.set_random_seed(96)

#set the sequential model with 3 layers
layer1 = layers.Dense(units=2, activation='relu', name='layer1')
layer2 = layers.Dense(units=3, activation='relu', name='layer2')
layer3 = layers.Dense(units=4, name='layer3')
#call the sequential model
x = tf.ones((3,3))
y = layer3(layer2(layer1(x)))
y


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.69751585, -0.89238983, -0.15444523, -0.1564925 ],
       [-0.69751585, -0.89238983, -0.15444523, -0.1564925 ],
       [-0.69751585, -0.89238983, -0.15444523, -0.1564925 ]],
      dtype=float32)>

We conclude it is actually the same Sequential model constructions

In [6]:
layer = layers.Dense(units=3)
layer.weights  # Empty

[]

In [5]:
# layer weights after entering the inputs
x = tf.ones((1,4))
y = layer(x)
layer.weights

[<tf.Variable 'dense/kernel:0' shape=(4, 3) dtype=float32, numpy=
 array([[ 0.11403227,  0.37307203, -0.3158257 ],
        [ 0.2862811 , -0.8418399 , -0.49150178],
        [-0.90049213, -0.6906144 ,  0.05955148],
        [-0.16262174,  0.22929382, -0.50861406]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]

In [4]:
model = keras.Sequential(
    [
        layers.Dense(2, activation="relu"),
        layers.Dense(3, activation="relu"),
        layers.Dense(4),
    ]
)

In [6]:
# error type of the model when there is not inputs
model.weights

ValueError: Weights for model 'sequential_1' have not yet been created. Weights are created when the model is first called on inputs or `build()` is called with an `input_shape`.

In [8]:
model.summary()

ValueError: This model has not yet been built. Build the model first by calling `build()` or by calling the model on a batch of data.

In [6]:
#building the model
model = keras.Sequential(
    [
        layers.Dense(2, activation="relu"),
        layers.Dense(3, activation="relu"),
        layers.Dense(4),
    ]
) 

x = tf.ones((2, 4))
y = model(x)
print("Number of weights after calling the model:", len(model.weights))  # 6

Number of weights after calling the model: 6


In [7]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (2, 2)                    10        
                                                                 
 dense_7 (Dense)             (2, 3)                    9         
                                                                 
 dense_8 (Dense)             (2, 4)                    16        
                                                                 
Total params: 35
Trainable params: 35
Non-trainable params: 0
_________________________________________________________________


In [21]:
#step-by-step model display
model = keras.Sequential(
    [
        keras.Input(shape=(4,)),
        layers.Dense(2, activation="relu"),
        layers.Dense(3),
    ]
) 

In [22]:
model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_15 (Dense)            (None, 2)                 10        
                                                                 
 dense_16 (Dense)            (None, 3)                 9         
                                                                 
Total params: 19
Trainable params: 19
Non-trainable params: 0
_________________________________________________________________


In [23]:
model.weights

[<tf.Variable 'dense_15/kernel:0' shape=(4, 2) dtype=float32, numpy=
 array([[ 0.2468965 , -0.3607421 ],
        [-0.6160872 , -0.09327173],
        [-0.35170126, -0.9121363 ],
        [-0.15791225, -0.61642647]], dtype=float32)>,
 <tf.Variable 'dense_15/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'dense_16/kernel:0' shape=(2, 3) dtype=float32, numpy=
 array([[-0.6551687 , -0.17583728, -0.05381632],
        [ 0.9569249 , -0.41870528, -1.0778964 ]], dtype=float32)>,
 <tf.Variable 'dense_16/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]