In [2]:
import tensorflow as tf

2024-02-17 13:58:35.346926: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-02-17 13:58:35.346991: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-02-17 13:58:35.372024: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-02-17 13:58:35.468508: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-17 13:58:36.565725: W tensorflow/compiler/tf2

In [11]:
x = tf.constant(
    [
        [1,2,3],
        [4,5,6]
    ], dtype = tf.float32
)
print(x)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [12]:
print(x.shape)
print(x.dtype)

(2, 3)
<dtype: 'float32'>


In [13]:
tf.transpose(x)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 4.],
       [2., 5.],
       [3., 6.]], dtype=float32)>

In [16]:
tf.nn.softmax(x, axis=-1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.09003057, 0.24472848, 0.6652409 ],
       [0.09003057, 0.24472848, 0.6652409 ]], dtype=float32)>

In [21]:
# generating the softmax function

import numpy as np

vector = np.array([1,2,3])

soft = []
for i in range(vector.shape[0]):
    result = np.exp(vector[i]) / (np.sum(np.exp(vector)))
    soft.append(result)
    
print(soft)

[0.09003057317038046, 0.24472847105479767, 0.6652409557748219]


In [20]:
import numpy as np

vector = np.array([1,2,3])
vector[0]

1