In [1]:
import tensorflow as tf
import keras
from keras import layers
import numpy as np

2024-03-23 11:55:40.762788: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-23 11:55:45.920856: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [14]:
#set seed
tf.keras.utils.set_random_seed(96)

#set the sequential model with 3 layers
model = keras.Sequential(
    [
        layers.Dense(units=2, activation='relu', name='layer1'),
        layers.Dense(units=3, activation='relu', name='layer2'),
        layers.Dense(units=4, name='layer3'),

    ]
)

#call the sequential model
x = tf.ones((3,3))
y = model(x)
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.69751585, -0.89238983, -0.15444523, -0.1564925 ],
       [-0.69751585, -0.89238983, -0.15444523, -0.1564925 ],
       [-0.69751585, -0.89238983, -0.15444523, -0.1564925 ]],
      dtype=float32)>

In [66]:
#equivalent model to the above

#set seed
tf.keras.utils.set_random_seed(96)

#set the sequential model with 3 layers
layer1 = layers.Dense(units=2, activation='relu', name='layer1')
layer2 = layers.Dense(units=3, activation='relu', name='layer2')
layer3 = layers.Dense(units=4, name='layer3')
#call the sequential model
x = tf.ones((3,3))
y = layer3(layer2(layer1(x)))
y


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.69751585, -0.89238983, -0.15444523, -0.1564925 ],
       [-0.69751585, -0.89238983, -0.15444523, -0.1564925 ],
       [-0.69751585, -0.89238983, -0.15444523, -0.1564925 ]],
      dtype=float32)>

We conclude it is actually the same Sequential model constructions