In [38]:
import tensorflow as tf
import keras
from keras import layers
import numpy as np

In [65]:
#set the sequential model with 3 layers
tf.keras.utils.set_random_seed(96)
model = keras.Sequential(
    [
        layers.Dense(units=2, activation='relu', name='layer1'),
        layers.Dense(units=3, activation='relu', name='layer2'),
        layers.Dense(units=4, name='layer3'),

    ]
)

#call the sequential model
x = tf.ones((3,3))
y = model(x)
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.69751585, -0.89238983, -0.15444523, -0.1564925 ],
       [-0.69751585, -0.89238983, -0.15444523, -0.1564925 ],
       [-0.69751585, -0.89238983, -0.15444523, -0.1564925 ]],
      dtype=float32)>

In [66]:
#equivalent model to the above
tf.keras.utils.set_random_seed(96)
layer1 = layers.Dense(units=2, activation='relu', name='layer1')
layer2 = layers.Dense(units=3, activation='relu', name='layer2')
layer3 = layers.Dense(units=4, name='layer3')
#call the sequential model
x = tf.ones((3,3))
y = layer3(layer2(layer1(x)))
y


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.69751585, -0.89238983, -0.15444523, -0.1564925 ],
       [-0.69751585, -0.89238983, -0.15444523, -0.1564925 ],
       [-0.69751585, -0.89238983, -0.15444523, -0.1564925 ]],
      dtype=float32)>